name: whisper
services:
    whisper:
        container_name: whisper
        volumes:
            - /path/to/your/videos:/videos
        ports:
            - 9003:2147
        image: zhangyiming748/whisper
        environment:
            - SQLSERVICE = 192.168.1.9:3306
            - LocalDeeplxService = 192.168.1.9:3389
        # docker run -e MYSQL=192.168.1.9:3306